
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: christopherjavalord@gmail.com
    password: pswj kvkm pwtb ypwp
    properties:
      mail:
        smtp:
        ssl:
          auth: true
          starttls:
            enable: true
    
